### PR TITLE
Add RViz2

### PR DESCRIPTION
**Pull request by atinfinity**
I add to build RViz2. So, I back-ported the following package from iron branch.

- console_bridge_vendor
- rviz_ogre_vendor

I checked on the following environment.

- macOS Sonoma 14.0
- M1 MacBook Air

```shell
rviz2
```

スクリーンショット 2023-12-20 22 49 13

### CODE REVIEW

**Comment by Ar-Ray-code** [comment]
image

I also did it! Thanks a lot 😄 
- MacBook Air2 (m2-arm64, 16GB)
- Mac OS : Sonoma 14.1.1（23B81）
- 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023
- Xcode/xcodebuild : Version 15.1 (15C65)

### Dependencies to be added
- empy == 3.3.4

**Comment by atinfinity** [comment]
@Ar-Ray-code Thank you for your check! 

> ### Dependencies to be added
> * empy == 3.3.4

I read [current install_guide.md](https://github.com/TakanoTaiga/ros2_m1_native/blob/535cb002ac61eef192b74350c4ec92af902b1653/install_guide.md). There is the following description.

```shell
python3.11 -m pip install -U \
      argcomplete catkin_pkg colcon-common-extensions coverage \
      cryptography empy flake8 flake8-blind-except==0.1.1 flake8-builtins \
      flake8-class-newline flake8-comprehensions flake8-deprecated \
      flake8-docstrings flake8-import-order flake8-quotes \
      importlib-metadata lark==1.1.1 lxml matplotlib mock mypy==0.931 netifaces \
      nose pep8 psutil pydocstyle pydot pygraphviz pyparsing==2.4.7 \
      pytest-mock rosdep rosdistro setuptools==59.6.0 vcstool
```

So, `empy` package was installed.

**Comment by Ar-Ray-code** [comment]
I followed that procedure and empy==4 was installed.
empy==4 is the cause of the ROS2 build failure. (related issue https://github.com/colcon/colcon-core/issues/602 )

**Comment by atinfinity** [comment]
@Ar-Ray-code Thank you for your information. I understood. I fixed in <https://github.com/TakanoTaiga/ros2_m1_native/pull/5/commits/35997029a2516f8423bec0546239ba2957329b11>.

**Comment by takanotaiga** [comment]
@atinfinity
Thank you for your Pull Request. When I tested it in my environment, I encountered the following error. Is there a solution to enhance the reproducibility of the build?

Test Environment:
- M1 Max 64GB RAM (Virtual M1 Max v8-core 16GB)
- OS: macOS Sonoma 14.2.1 (MiniVirtual (Virtual Machine))
- Environment set up from scratch (including tests with Xcode installed)

Encountered Error:
```
xcode select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance In file included from /Users/taiga/Desktop/ros?_ml._native/build/rvizogre_vendor/ogre-v1.12.10-prefix/src/ogre-v1.12.10/0greMain/src/0greASTCCodec.cpp:29:
In file included from /Users/taiga/Desktop/ros?_ml._native/build/rvizogre_vendor/ogre-v1.12.10-prefix/src/ogre-v1.12.10/0greMain/src/0greStableHeaders.h:45:
In file included from /Users/taiga/Desktop/ros?ml_native/build/rvizogre_vendor/ogre-v1.12.10-prefix/src/ogre-v1.12.10/0greMain/include/OgrePrerequisites.h:35:
/Users/taiga/Desktop/ros?_m/_native/build/rviz_ogre_vendor/ogre-v1.12.10-prefix/src/ogre-v1.12.10/0greMain/include/0grePlatform.h:183:13: fatal error: 'Availability.h' file not found

# include "Availability.h"
```
スクリーンショット 2023-12-22 18 17 11

**Comment by atinfinity** [comment]
@TakanoTaiga 

> xcode select: error: tool 'xcodebuild' requires Xcode, but active developer directory

Did you install Xcode? According to this error message it appears that Xcode is not installed.
You can check by executing `xcodebuild -version`.

```shell
$ xcodebuild -version
Xcode 15.1
Build version 15C65
```

> \# include "Availability.h"

OGRE includes "Availability.h". This header file is provided by MacOSX SDK.
<https://github.com/OGRECave/ogre/blob/v1.12.10/OgreMain/include/OgrePlatform.h#L182-L188>

I could find this header file.

```shell
$ find /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform -name Availability.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/Availability.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/Availability.h
```

**Comment by takanotaiga** [comment]
I was able to build in this environment. Despite having Xcode installed, I discovered a bug in Xcode that prevents access from the command line. @TakanoTaiga will address the Xcode bug in a separate PR later. Finally, I would like to thank everyone who contributed to this PR.

**Pull request merged**
